from yacs.config import CfgNode as CN

_C = CN()

# max number of keyframes
_C.BUFFER_SIZE = 4096

# bias patch selection towards high gradient regions?
_C.CENTROID_SEL_STRAT = 'RANDOM'

# VO config (increase for better accuracy)
_C.PATCHES_PER_FRAME = 80
_C.REMOVAL_WINDOW = 20
_C.OPTIMIZATION_WINDOW = 12
_C.PATCH_LIFETIME = 12

# threshold for keyframe removal
_C.KEYFRAME_INDEX = 4
_C.KEYFRAME_THRESH = 12.5

# camera motion model
_C.MOTION_MODEL = 'DAMPED_LINEAR'
_C.MOTION_DAMPING = 0.5

_C.MIXED_PRECISION = True

# covariance adaptive parameters
_C.COV_STEEPNESS = 10.0  # steepness parameter for sigmoid mapping
_C.COV_THRESHOLD = 2.0   # threshold parameter for sigmoid mapping

# variance threshold for patch filtering
_C.VAR_THRESHOLD = 1.0   # threshold for filtering patches with high variance

# covariance adaptive weight
_C.USE_COV_ADAPTIVE = True  # whether to use covariance adaptive weight (for both initialization and regular updates)

# depth prior usage
_C.USE_DEPTH_PRIOR = True  # whether to use depth prior from PI3 (if False, confidences will be set to 0)

# dynamic filtering
_C.STATIC_MASK_THRESH = 0.4  # threshold for static region detection (static_mask < STATIC_MASK_THRESH)

# PI3 frame range for inference
_C.PI3_FRAME_RANGE = 5  # number of frames to use for PI3 inference

# demo outputs
_C.SAVE_RENDERED_IMAGES = True
_C.SAVE_GAUSSIAN_MAP = False

# Gaussian-SLAM integration
_C.GAUSSIAN_MAPPING = False
_C.GAUSSIAN_USE_RENDERER = True
_C.GAUSSIAN_WINDOW_SIZE = 10
_C.GAUSSIAN_INIT_WINDOW_SIZE = 5
_C.GAUSSIAN_MIN_FRAME_GAP = 1
_C.GAUSSIAN_DYNAMIC_THRESH = 0.4
_C.GAUSSIAN_STATIC_RATIO_THRESH = 0.6
_C.GAUSSIAN_INIT_CONF_THRESH = 0.1
_C.GAUSSIAN_INIT_OPT_ITERS = 40
_C.GAUSSIAN_OPT_ITERS = 1
_C.GAUSSIAN_FINAL_REFINEMENT_ITERS = 2000
_C.GAUSSIAN_DENSIFY_EVERY = 1500
_C.GAUSSIAN_OPACITY_RESET_EVERY = 750
_C.GAUSSIAN_VISIBILITY_RESET_THRESHOLD = 0.35
_C.GAUSSIAN_PRUNE_THRESH = 0.01
_C.GAUSSIAN_DEFORM_ON_BA = True
_C.GAUSSIAN_SAVE_DIR = "gaussian_map"
_C.GAUSSIAN_MIN_MOTION_SCORE = 0.02
_C.GAUSSIAN_QUEUE_SIZE = 64
_C.GAUSSIAN_SH_DEGREE = 3
_C.GAUSSIAN_MAX_INIT_POINTS_PER_FRAME = 2500
_C.GAUSSIAN_INIT_POINT_SAMPLE_RATIO = 1.0
_C.GAUSSIAN_MIN_TRANSLATION = 0.05
_C.GAUSSIAN_FORCE_KEYFRAME_EVERY = 8
_C.GAUSSIAN_INIT_VOXEL_SIZE = 0.015
_C.GAUSSIAN_NEW_POINT_OPACITY_THRESH = 0.35
_C.GAUSSIAN_NEW_POINT_DEPTH_REL_THRESH = 0.20
_C.GAUSSIAN_TEXTURE_WEIGHT = 0.75
_C.GAUSSIAN_NEW_POINT_RESIDUAL_THRESH = 0.12
_C.GAUSSIAN_GRADIENT_LOSS_WEIGHT = 0.15
_C.GAUSSIAN_DEPTH_LOSS_WEIGHT = 0.5
_C.GAUSSIAN_DEPTH_RELATIVE_LOSS_WEIGHT = 0.2
_C.GAUSSIAN_DEPTH_GRADIENT_LOSS_WEIGHT = 0.1
_C.GAUSSIAN_SOFT_STATIC_POWER = 2.0
_C.GAUSSIAN_CONFIDENCE_POWER = 1.0
_C.GAUSSIAN_STATIC_WEIGHT_FLOOR = 0.05
_C.GAUSSIAN_POSE_DEPTH_MIN_SCALE = 0.7
_C.GAUSSIAN_POSE_DEPTH_MAX_SCALE = 1.35
_C.GAUSSIAN_MAX_TOTAL_POINTS = 30000
_C.GAUSSIAN_MIN_POINTS_PER_FRAME = 400

# Loop closure
_C.LOOP_CLOSURE = False
_C.BACKEND_THRESH = 64.0
_C.MAX_EDGE_AGE = 1000
_C.GLOBAL_OPT_FREQ = 15

# Classic loop closure
_C.CLASSIC_LOOP_CLOSURE = False
_C.LOOP_CLOSE_WINDOW_SIZE = 3
_C.LOOP_RETR_THRESH = 0.04

cfg = _C
