### DPVO Config File ###

# VO config (increase for better accuracy)
PATCHES_PER_FRAME: 128
REMOVAL_WINDOW: 22
OPTIMIZATION_WINDOW: 10
PATCH_LIFETIME: 15

# threshold for keyframe removal
KEYFRAME_THRESH: 15.0

# camera motion model
MOTION_MODEL: 'DAMPED_LINEAR'
MOTION_DAMPING: 0.5

MIXED_PRECISION: True

CENTROID_SEL_STRAT: 'GRADIENT_BIAS' # 'RANDOM' or 'GRADIENT_BIAS'

COV_STEEPNESS: 10.0  # steepness parameter for sigmoid

COV_THRESHOLD: 1.5   # threshold parameter for sigmoid

VAR_THRESHOLD: 0.5   # threshold for filtering patches with high variance

USE_COV_ADAPTIVE: True  # whether to use covariance adaptive weight

USE_DEPTH_PRIOR: True  # whether to use depth prior from PI3 (if False, confidences will be set to 0)

STATIC_MASK_THRESH: 0.4  # threshold for static region detection (static_mask < STATIC_MASK_THRESH)

PI3_FRAME_RANGE: 5  # number of frames to use for PI3 inference

SAVE_RENDERED_IMAGES: True
SAVE_GAUSSIAN_MAP: False
GAUSSIAN_MAPPING: True
GAUSSIAN_WINDOW_SIZE: 10
GAUSSIAN_INIT_WINDOW_SIZE: 5
GAUSSIAN_MIN_FRAME_GAP: 1
GAUSSIAN_DYNAMIC_THRESH: 0.4
GAUSSIAN_STATIC_RATIO_THRESH: 0.6
GAUSSIAN_INIT_CONF_THRESH: 0.1
GAUSSIAN_INIT_OPT_ITERS: 40
GAUSSIAN_OPT_ITERS: 1
GAUSSIAN_FINAL_REFINEMENT_ITERS: 2000
GAUSSIAN_DENSIFY_EVERY: 1500
GAUSSIAN_OPACITY_RESET_EVERY: 750
GAUSSIAN_VISIBILITY_RESET_THRESHOLD: 0.35
GAUSSIAN_PRUNE_THRESH: 0.01
GAUSSIAN_DEFORM_ON_BA: True
GAUSSIAN_QUEUE_SIZE: 64
GAUSSIAN_MIN_MOTION_SCORE: 0.02
GAUSSIAN_MIN_TRANSLATION: 0.05
GAUSSIAN_FORCE_KEYFRAME_EVERY: 8
GAUSSIAN_SH_DEGREE: 3
GAUSSIAN_MAX_INIT_POINTS_PER_FRAME: 2500
GAUSSIAN_INIT_POINT_SAMPLE_RATIO: 1.0
GAUSSIAN_INIT_VOXEL_SIZE: 0.01
GAUSSIAN_NEW_POINT_OPACITY_THRESH: 0.35
GAUSSIAN_NEW_POINT_DEPTH_REL_THRESH: 0.20
GAUSSIAN_TEXTURE_WEIGHT: 0.75
GAUSSIAN_NEW_POINT_RESIDUAL_THRESH: 0.12
GAUSSIAN_DSSIM_WEIGHT: 0.3
GAUSSIAN_GRADIENT_LOSS_WEIGHT: 0.15
GAUSSIAN_DEPTH_LOSS_WEIGHT: 0.5
GAUSSIAN_DEPTH_RELATIVE_LOSS_WEIGHT: 0.2
GAUSSIAN_DEPTH_GRADIENT_LOSS_WEIGHT: 0.1
GAUSSIAN_SOFT_STATIC_POWER: 2.0
GAUSSIAN_CONFIDENCE_POWER: 1.0
GAUSSIAN_STATIC_WEIGHT_FLOOR: 0.05
GAUSSIAN_POSE_DEPTH_MIN_SCALE: 0.7
GAUSSIAN_POSE_DEPTH_MAX_SCALE: 1.35
GAUSSIAN_MAX_TOTAL_POINTS: 30000
GAUSSIAN_MIN_POINTS_PER_FRAME: 400
